kind: pipeline
type: docker
name: add-server-ci

step:
- name: backend
  images: golang:1.13-alpine
  commands:
  - go build 
  - go test
  - echo "hello"
  when: 
    branch:
    - master
    
- name: backend
  images: golang:1.13-alpine
  commands:
  - go build 
  - go test
  - echo "123"
