---
kind: pipeline
type: exec
name: deploy-master

platform:
  os: linux
  ar—Åh: amd64

steps:
- name: copy
  commands:
  - cp -rf ./ /srv/fix.moe

- name: install
  commands:
  - source /root/.nvm/nvm.sh
  - cd /srv/fix.moe
  - npm install

- name: run
  commands:
  - source /root/.nvm/nvm.sh
  - export PM2_HOME=/root/.pm2
  - cd /srv/fix.moe
  - pm2 stop fix.moe
  - pm2 delete fix.moe
  - pm2 start npm --name fix.moe -- run start

trigger:
  branch:
  - master
  event:
  - push
